### ISSUE TITLE
Project 2: Presentation Requirements

### ISSUE THREAD

**Issue by crichID** [tour-guide/tour-guide-web#2]
Here are the presentation requirements for our project. I'm opening this issue so we can drop ideas here as they come up!

## Presentation Requirements
​
Use this [project presentation template](https://docs.google.com/presentation/d/1_u8TKy5zW5UlrVQVnyDEZ0unGI2tjQPDEpA0FNuBKAw/edit?usp=sharing) to address the following: 
​
* Elevator pitch: a one minute description of your application
* Concept: What is your user story? What was your motivation for development?
* Process: What were the technologies used? How were tasks and roles broken down and assigned? What challenges did you encounter? What were your successes?
* Demo: Show your stuff!
* Directions for Future Development
* Links to to the deployed application and the GitHub repository
​

**Comment by cynthiarich** [comment]
## Ideas for future development

- Transcribed audio
- Monetize it and charge for tours

**Comment by dropcat13** [comment]
Future Monetization - could there be a professional tour leader section. For someone who wants to lead paid tours.

**Comment by dropcat13** [comment]
Future - Get trending stories based on views over the last week/month. Utilizing some sort of view counter in the database.
