### ISSUE TITLE
Slugify tour titles

### ISSUE THREAD

**Issue by cynthiarich** [tour-guide/tour-guide-web#20]
The code for this should go in the db model and look something like this:

```
const slugify = require('slugify');

Story.addHook('beforeValidate', Story => {
    Story.slug = slugify(Story.title, { lower: true })
    return Story
  })
```

Docs on the hook are [here](https://sequelize.org/master/manual/hooks.html)

**Comment by dropcat13** [comment]
Great! I'll add that :)

**Comment by cynthiarich** [comment]
You are the best @dropcat13! Thank you! For what it's worth, that code was a guess :wink:

**Comment by cynthiarich** [comment]
This was done in #31 - closing this issue now!
